export type SurahStatus = 'not-started' | 'in-progress' | 'weak-memorization' | 'needs-revision' | 'strong-memorization';

export interface Surah {
  id: number;
  name: string;
  englishName: string;
  revelationType: 'Meccan' | 'Medinan';
  numberOfAyahs: number;
  status: SurahStatus;
}

export const quranData: Surah[] = [
    { id: 1, name: "Al-Fatihah", englishName: "The Opening", numberOfAyahs: 7, revelationType: "Meccan", status: "strong-memorization" },
    { id: 2, name: "Al-Baqarah", englishName: "The Cow", numberOfAyahs: 286, revelationType: "Medinan", status: "in-progress" },
    { id: 3, name: "Aal-E-Imran", englishName: "The Family of Imran", numberOfAyahs: 200, revelationType: "Medinan", status: "in-progress" },
    { id: 4, name: "An-Nisa", englishName: "The Women", numberOfAyahs: 176, revelationType: "Medinan", status: "not-started" },
    { id: 5, name: "Al-Ma'idah", englishName: "The Table Spread", numberOfAyahs: 120, revelationType: "Medinan", status: "not-started" },
    { id: 6, name: "Al-An'am", englishName: "The Cattle", numberOfAyahs: 165, revelationType: "Meccan", status: "not-started" },
    { id: 7, name: "Al-A'raf", englishName: "The Heights", numberOfAyahs: 206, revelationType: "Meccan", status: "not-started" },
    { id: 8, name: "Al-Anfal", englishName: "The Spoils of War", numberOfAyahs: 75, revelationType: "Medinan", status: "not-started" },
    { id: 9, name: "At-Tawbah", englishName: "The Repentance", numberOfAyahs: 129, revelationType: "Medinan", status: "not-started" },
    { id: 10, name: "Yunus", englishName: "Jonah", numberOfAyahs: 109, revelationType: "Meccan", status: "not-started" },
    { id: 11, name: "Hud", englishName: "Hud", numberOfAyahs: 123, revelationType: "Meccan", status: "not-started" },
    { id: 12, name: "Yusuf", englishName: "Joseph", numberOfAyahs: 111, revelationType: "Meccan", status: "strong-memorization" },
    { id: 13, name: "Ar-Ra'd", englishName: "The Thunder", numberOfAyahs: 43, revelationType: "Meccan", status: "not-started" },
    { id: 14, name: "Ibrahim", englishName: "Abraham", numberOfAyahs: 52, revelationType: "Meccan", status: "not-started" },
    { id: 15, name: "Al-Hijr", englishName: "The Rocky Tract", numberOfAyahs: 99, revelationType: "Meccan", status: "not-started" },
    { id: 16, name: "An-Nahl", englishName: "The Bee", numberOfAyahs: 128, revelationType: "Meccan", status: "not-started" },
    { id: 17, name: "Al-Isra", englishName: "The Night Journey", numberOfAyahs: 111, revelationType: "Meccan", status: "not-started" },
    { id: 18, name: "Al-Kahf", englishName: "The Cave", numberOfAyahs: 110, revelationType: "Meccan", status: "in-progress" },
    { id: 19, name: "Maryam", englishName: "Mary", numberOfAyahs: 98, revelationType: "Meccan", status: "not-started" },
    { id: 20, name: "Taha", englishName: "Ta-Ha", numberOfAyahs: 135, revelationType: "Meccan", status: "not-started" },
    { id: 21, name: "Al-Anbiya", englishName: "The Prophets", numberOfAyahs: 112, revelationType: "Meccan", status: "not-started" },
    { id: 22, name: "Al-Hajj", englishName: "The Pilgrimage", numberOfAyahs: 78, revelationType: "Medinan", status: "not-started" },
    { id: 23, name: "Al-Mu'minun", englishName: "The Believers", numberOfAyahs: 118, revelationType: "Meccan", status: "not-started" },
    { id: 24, name: "An-Nur", englishName: "The Light", numberOfAyahs: 64, revelationType: "Medinan", status: "not-started" },
    { id: 25, name: "Al-Furqan", englishName: "The Criterion", numberOfAyahs: 77, revelationType: "Meccan", status: "not-started" },
    { id: 26, name: "Ash-Shu'ara", englishName: "The Poets", numberOfAyahs: 227, revelationType: "Meccan", status: "not-started" },
    { id: 27, name: "An-Naml", englishName: "The Ant", numberOfAyahs: 93, revelationType: "Meccan", status: "not-started" },
    { id: 28, name: "Al-Qasas", englishName: "The Stories", numberOfAyahs: 88, revelationType: "Meccan", status: "not-started" },
    { id: 29, name: "Al-Ankabut", englishName: "The Spider", numberOfAyahs: 69, revelationType: "Meccan", status: "not-started" },
    { id: 30, name: "Ar-Rum", englishName: "The Romans", numberOfAyahs: 60, revelationType: "Meccan", status: "not-started" },
    { id: 31, name: "Luqman", englishName: "Luqman", numberOfAyahs: 34, revelationType: "Meccan", status: "not-started" },
    { id: 32, name: "As-Sajdah", englishName: "The Prostration", numberOfAyahs: 30, revelationType: "Meccan", status: "not-started" },
    { id: 33, name: "Al-Ahzab", englishName: "The Combined Forces", numberOfAyahs: 73, revelationType: "Medinan", status: "not-started" },
    { id: 34, name: "Saba", englishName: "Sheba", numberOfAyahs: 54, revelationType: "Meccan", status: "not-started" },
    { id: 35, name: "Fatir", englishName: "The Originator", numberOfAyahs: 45, revelationType: "Meccan", status: "not-started" },
    { id: 36, name: "Ya-Sin", englishName: "Ya Sin", numberOfAyahs: 83, revelationType: "Meccan", status: "strong-memorization" },
    { id: 37, name: "As-Saffat", englishName: "Those who set the Ranks", numberOfAyahs: 182, revelationType: "Meccan", status: "not-started" },
    { id: 38, name: "Sad", englishName: "The Letter 'Saad'", numberOfAyahs: 88, revelationType: "Meccan", status: "not-started" },
    { id: 39, name: "Az-Zumar", englishName: "The Troops", numberOfAyahs: 75, revelationType: "Meccan", status: "not-started" },
    { id: 40, name: "Ghafir", englishName: "The Forgiver", numberOfAyahs: 85, revelationType: "Meccan", status: "not-started" },
    { id: 41, name: "Fussilat", englishName: "Explained in Detail", numberOfAyahs: 54, revelationType: "Meccan", status: "not-started" },
    { id: 42, name: "Ash-Shuraa", englishName: "The Consultation", numberOfAyahs: 53, revelationType: "Meccan", status: "not-started" },
    { id: 43, name: "Az-Zukhruf", englishName: "The Ornaments of Gold", numberOfAyahs: 89, revelationType: "Meccan", status: "not-started" },
    { id: 44, name: "Ad-Dukhan", englishName: "The Smoke", numberOfAyahs: 59, revelationType: "Meccan", status: "not-started" },
    { id: 45, name: "Al-Jathiyah", englishName: "The Crouching", numberOfAyahs: 37, revelationType: "Meccan", status: "not-started" },
    { id: 46, name: "Al-Ahqaf", englishName: "The Wind-Curved Sandhills", numberOfAyahs: 35, revelationType: "Meccan", status: "not-started" },
    { id: 47, name: "Muhammad", englishName: "Muhammad", numberOfAyahs: 38, revelationType: "Medinan", status: "not-started" },
    { id: 48, name: "Al-Fath", englishName: "The Victory", numberOfAyahs: 29, revelationType: "Medinan", status: "not-started" },
    { id: 49, name: "Al-Hujurat", englishName: "The Rooms", numberOfAyahs: 18, revelationType: "Medinan", status: "not-started" },
    { id: 50, name: "Qaf", englishName: "The Letter 'Qaf'", numberOfAyahs: 45, revelationType: "Meccan", status: "not-started" },
    { id: 51, name: "Adh-Dhariyat", englishName: "The Winnowing Winds", numberOfAyahs: 60, revelationType: "Meccan", status: "not-started" },
    { id: 52, name: "At-Tur", englishName: "The Mount", numberOfAyahs: 49, revelationType: "Meccan", status: "not-started" },
    { id: 53, name: "An-Najm", englishName: "The Star", numberOfAyahs: 62, revelationType: "Meccan", status: "not-started" },
    { id: 54, name: "Al-Qamar", englishName: "The Moon", numberOfAyahs: 55, revelationType: "Meccan", status: "not-started" },
    { id: 55, name: "Ar-Rahman", englishName: "The Most Merciful", numberOfAyahs: 78, revelationType: "Medinan", status: "strong-memorization" },
    { id: 56, name: "Al-Waqi'ah", englishName: "The Inevitable", numberOfAyahs: 96, revelationType: "Meccan", status: "in-progress" },
    { id: 57, name: "Al-Hadid", englishName: "The Iron", numberOfAyahs: 29, revelationType: "Medinan", status: "not-started" },
    { id: 58, name: "Al-Mujadila", englishName: "The Pleading Woman", numberOfAyahs: 22, revelationType: "Medinan", status: "not-started" },
    { id: 59, name: "Al-Hashr", englishName: "The Exile", numberOfAyahs: 24, revelationType: "Medinan", status: "not-started" },
    { id: 60, name: "Al-Mumtahanah", englishName: "She that is to be examined", numberOfAyahs: 13, revelationType: "Medinan", status: "not-started" },
    { id: 61, name: "As-Saf", englishName: "The Ranks", numberOfAyahs: 14, revelationType: "Medinan", status: "not-started" },
    { id: 62, name: "Al-Jumu'ah", englishName: "The Congregation, Friday", numberOfAyahs: 11, revelationType: "Medinan", status: "not-started" },
    { id: 63, name: "Al-Munafiqun", englishName: "The Hypocrites", numberOfAyahs: 11, revelationType: "Medinan", status: "not-started" },
    { id: 64, name: "At-Taghabun", englishName: "The Mutual Disillusion", numberOfAyahs: 18, revelationType: "Medinan", status: "not-started" },
    { id: 65, name: "At-Talaq", englishName: "The Divorce", numberOfAyahs: 12, revelationType: "Medinan", status: "not-started" },
    { id: 66, name: "At-Tahrim", englishName: "The Prohibition", numberOfAyahs: 12, revelationType: "Medinan", status: "not-started" },
    { id: 67, name: "Al-Mulk", englishName: "The Sovereignty", numberOfAyahs: 30, revelationType: "Meccan", status: "strong-memorization" },
    { id: 68, name: "Al-Qalam", englishName: "The Pen", numberOfAyahs: 52, revelationType: "Meccan", status: "not-started" },
    { id: 69, name: "Al-Haqqah", englishName: "The Reality", numberOfAyahs: 52, revelationType: "Meccan", status: "not-started" },
    { id: 70, name: "Al-Ma'arij", englishName: "The Ascending Stairways", numberOfAyahs: 44, revelationType: "Meccan", status: "not-started" },
    { id: 71, name: "Nuh", englishName: "Noah", numberOfAyahs: 28, revelationType: "Meccan", status: "not-started" },
    { id: 72, name: "Al-Jinn", englishName: "The Jinn", numberOfAyahs: 28, revelationType: "Meccan", status: "not-started" },
    { id: 73, name: "Al-Muzzammil", englishName: "The Enshrouded One", numberOfAyahs: 20, revelationType: "Meccan", status: "not-started" },
    { id: 74, name: "Al-Muddaththir", englishName: "The Cloaked One", numberOfAyahs: 56, revelationType: "Meccan", status: "not-started" },
    { id: 75, name: "Al-Qiyamah", englishName: "The Resurrection", numberOfAyahs: 40, revelationType: "Meccan", status: "not-started" },
    { id: 76, name: "Al-Insan", englishName: "Man", numberOfAyahs: 31, revelationType: "Medinan", status: "not-started" },
    { id: 77, name: "Al-Mursalat", englishName: "The Emissaries", numberOfAyahs: 50, revelationType: "Meccan", status: "not-started" },
    { id: 78, name: "An-Naba", englishName: "The Tidings", numberOfAyahs: 40, revelationType: "Meccan", status: "in-progress" },
    { id: 79, name: "An-Nazi'at", englishName: "Those who drag forth", numberOfAyahs: 46, revelationType: "Meccan", status: "not-started" },
    { id: 80, name: "'Abasa", englishName: "He Frowned", numberOfAyahs: 42, revelationType: "Meccan", status: "not-started" },
    { id: 81, name: "At-Takwir", englishName: "The Overthrowing", numberOfAyahs: 29, revelationType: "Meccan", status: "not-started" },
    { id: 82, name: "Al-Infitar", englishName: "The Cleaving", numberOfAyahs: 19, revelationType: "Meccan", status: "not-started" },
    { id: 83, name: "Al-Mutaffifin", englishName: "The Defrauding", numberOfAyahs: 36, revelationType: "Meccan", status: "not-started" },
    { id: 84, name: "Al-Inshiqaq", englishName: "The Sundering", numberOfAyahs: 25, revelationType: "Meccan", status: "not-started" },
    { id: 85, name: "Al-Buruj", englishName: "The Mansions of the Stars", numberOfAyahs: 22, revelationType: "Meccan", status: "not-started" },
    { id: 86, name: "At-Tariq", englishName: "The Nightcommer", numberOfAyahs: 17, revelationType: "Meccan", status: "not-started" },
    { id: 87, name: "Al-A'la", englishName: "The Most High", numberOfAyahs: 19, revelationType: "Meccan", status: "strong-memorization" },
    { id: 88, name: "Al-Ghashiyah", englishName: "The Overwhelming", numberOfAyahs: 26, revelationType: "Meccan", status: "strong-memorization" },
    { id: 89, name: "Al-Fajr", englishName: "The Dawn", numberOfAyahs: 30, revelationType: "Meccan", status: "strong-memorization" },
    { id: 90, name: "Al-Balad", englishName: "The City", numberOfAyahs: 20, revelationType: "Meccan", status: "strong-memorization" },
    { id: 91, name: "Ash-Shams", englishName: "The Sun", numberOfAyahs: 15, revelationType: "Meccan", status: "strong-memorization" },
    { id: 92, name: "Al-Layl", englishName: "The Night", numberOfAyahs: 21, revelationType: "Meccan", status: "strong-memorization" },
    { id: 93, name: "Ad-Duhaa", englishName: "The Morning Hours", numberOfAyahs: 11, revelationType: "Meccan", status: "strong-memorization" },
    { id: 94, name: "Ash-Sharh", englishName: "The Consolation", numberOfAyahs: 8, revelationType: "Meccan", status: "strong-memorization" },
    { id: 95, name: "At-Tin", englishName: "The Fig", numberOfAyahs: 8, revelationType: "Meccan", status: "strong-memorization" },
    { id: 96, name: "Al-'Alaq", englishName: "The Clot", numberOfAyahs: 19, revelationType: "Meccan", status: "strong-memorization" },
    { id: 97, name: "Al-Qadr", englishName: "The Power, Fate", numberOfAyahs: 5, revelationType: "Meccan", status: "strong-memorization" },
    { id: 98, name: "Al-Bayyinah", englishName: "The Clear Proof", numberOfAyahs: 8, revelationType: "Medinan", status: "strong-memorization" },
    { id: 99, name: "Az-Zalzalah", englishName: "The Earthquake", numberOfAyahs: 8, revelationType: "Medinan", status: "strong-memorization" },
    { id: 100, name: "Al-'Adiyat", englishName: "The Courser", numberOfAyahs: 11, revelationType: "Meccan", status: "strong-memorization" },
    { id: 101, name: "Al-Qari'ah", englishName: "The Calamity", numberOfAyahs: 11, revelationType: "Meccan", status: "strong-memorization" },
    { id: 102, name: "At-Takathur", englishName: "The Piling Up", numberOfAyahs: 8, revelationType: "Meccan", status: "strong-memorization" },
    { id: 103, name: "Al-'Asr", englishName: "The Time", numberOfAyahs: 3, revelationType: "Meccan", status: "strong-memorization" },
    { id: 104, name: "Al-Humazah", englishName: "The Slanderer", numberOfAyahs: 9, revelationType: "Meccan", status: "strong-memorization" },
    { id: 105, name: "Al-Fil", englishName: "The Elephant", numberOfAyahs: 5, revelationType: "Meccan", status: "strong-memorization" },
    { id: 106, name: "Quraysh", englishName: "Quraysh", numberOfAyahs: 4, revelationType: "Meccan", status: "strong-memorization" },
    { id: 107, name: "Al-Ma'un", englishName: "The Small Kindnesses", numberOfAyahs: 7, revelationType: "Meccan", status: "strong-memorization" },
    { id: 108, name: "Al-Kawthar", englishName: "The Abundance", numberOfAyahs: 3, revelationType: "Meccan", status: "strong-memorization" },
    { id: 109, name: "Al-Kafirun", englishName: "The Disbelievers", numberOfAyahs: 6, revelationType: "Meccan", status: "strong-memorization" },
    { id: 110, name: "An-Nasr", englishName: "The Divine Support", numberOfAyahs: 3, revelationType: "Medinan", status: "strong-memorization" },
    { id: 111, name: "Al-Masad", englishName: "The Palm Fiber", numberOfAyahs: 5, revelationType: "Meccan", status: "strong-memorization" },
    { id: 112, name: "Al-Ikhlas", englishName: "The Sincerity", numberOfAyahs: 4, revelationType: "Meccan", status: "strong-memorization" },
    { id: 113, name: "Al-Falaq", englishName: "The Daybreak", numberOfAyahs: 5, revelationType: "Meccan", status: "strong-memorization" },
    { id: 114, name: "An-Nas", englishName: "Mankind", numberOfAyahs: 6, revelationType: "Meccan", status: "strong-memorization" }
];
